# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 7777777
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
